name: Project Automation

on:
  issues:
    types: [moved]

jobs:
  project_automation:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the card is in the 'Done' column
        id: check_done_column
        run: |
          if [[ ${{ github.event.project_card.column_name }} == 'Done' ]]; then
              echo "::set-output name=is_done::true"
          else
              echo "::set-output name=is_done::false"
          fi
        shell: bash

      - name: Close issue if it's in the 'Done' column
        if: steps.check_done_column.outputs.is_done == 'true'
        run: |
          # Extract the issue number from the issue URL
          ISSUE_URL="${{ github.event.project_card.content_url }}"
          ISSUE_NUMBER=$(basename "$ISSUE_URL")
          
          # Close the issue using the GitHub API
          GITHUB_TOKEN="${{ secrets.GH_TOKEN }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"
          
          # Use the API to close the issue
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" -d '{"state":"closed"}' "$API_URL"
        shell: bash
